# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

<<<<<<< HEAD
steps:
- script: echo Hello, world, changed!!
  displayName: 'Run a one-line script'
=======
# Pipelines > Stages > Jobs > Tasks(Steps)

jobs:
- job: Job1
  steps:
  - script: echo Job1 - Hello, world, changed!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job2
    displayName: 'Run a one-line script'
- job: Job3
  dependsOn: Job2
  steps:
  - script: echo Job3
    displayName: 'Run a one-line script'
>>>>>>> 030658be0a9561dceebb85b1a85e1a258833bf55

